version: '3.3'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - /swarm/portainer/data:/data
    networks:
      - proxy_net
      - agent_net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
          - "traefik.enable=true"
          - "traefik.docker.network=proxy_net"
          - "traefik.http.routers.portainer_router.rule=Host(`portainer.docker.internal`)"
          - "traefik.http.routers.portainer_router.service=portainer_service"
          - "traefik.http.routers.portainer_router.entrypoints=http,https"
          - "traefik.http.services.portainer_service.loadbalancer.server.port=9000"

networks:
  proxy_net:
    external: true