version: '3.3'

services:

  mysql:
    image: mysql:5.7
    networks:
        - db_net
    environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: keycloak
    MYSQL_USER: keycloak
    MYSQL_PASSWORD: password
    volumes:
    - /swarm/keycloak/mysql_data:/var/lib/mysql
    deploy:
        resources:
            limits:
                memory: 200M
        restart_policy:
            condition: on-failure
        placement:
            constraints:
                - "node.platform.os == linux"

  keycloak:
      image: jboss/keycloak:3.2.0.Final
      networks:
        - function_net
        - db_net
        - proxy_net
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      deploy:
        resources:
            limits:
                memory: 200M
        restart_policy:
            condition: on-failure
        placement:
            constraints:
                - "node.platform.os == linux"
            labels:
                - "traefik.enable=true"
                - "traefik.docker.network=proxy_net"
                - "traefik.http.routers.keycloak_router.rule=Host(`keycloak.docker.internal`)"
                - "traefik.http.routers.keycloak_router.service=keycloak_service"
                - "traefik.http.routers.keycloak_router.entrypoints=http,https"
                - "traefik.http.services.keycloak_service.loadbalancer.server.port=8080"

networks:
  db_net:
    external: true
  proxy_net:
    external: true
  function_net:
    external: true